### ISSUE TITLE
Errors out when starting wow

### ISSUE THREAD

**Issue by journeym** [idiomatic/HandyNotes_Achievements#9] opened 2018-09-14 18:42 UTC
Date: 2018-09-14 21:40:43
ID: 1
Error occured in: Global
Count: 1
Message: ...ievements\Libs/MapExcursion-1.0/MapExcursion-1.0.lua line 16:
   attempt to call global 'GetCurrentMapAreaID' (a nil value)
Debug:
   ...ievements\Libs/MapExcursion-1.0/MapExcursion-1.0.lua:16: MapExcursion()
   ...ndyNotes_Achievements\Libs/MapMap-1.0/MapMap-1.0.lua:33: Survey()
   ...ndyNotes_Achievements\Libs/MapMap-1.0/MapMap-1.0.lua:22: ?()
   ...ndyNotes_Achievements\Libs/MapMap-1.0/MapMap-1.0.lua:15:
      ...ndyNotes_Achievements\Libs/MapMap-1.0/MapMap-1.0.lua:14
Locals:
self = <table> {
 MapExcursion = <function> defined @Interface\AddOns\HandyNotes_Achievements\Libs/MapExcursion-1.0/MapExcursion-1.0.lua:9
}
fn = <function> defined @Interface\AddOns\HandyNotes_Achievements\Libs/MapMap-1.0/MapMap-1.0.lua:33
registry = <table> {
}
previousContinent = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'GetCurrentMapAreaID' (a nil value)"

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AddOnSkins, v3.93
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  Clique, vv80000-1.0.0
  ConfirmSP, v02.12
  DBMCore, v8.0.8
  DBMDefaultSkin, v
  DBMSoundEventsPack, v1.4
  DBMStatusBarTimers, v
  DBMVPEnglishfemale, v8.0.5
  ElvUI, v10.81
  ElvUIBFACurrencies, v1.00
  ElvUICliqueDatatext, v1.11
  ElvUISLE, v3.451
  HandyNotes, vv1.5.3
  HandyNotesAchievements, v0.4.20
  HandyNotesArathi, v0.1.0
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBFAHFTracker, v8.0.4
  HandyNotesCamelFigurines, v1.3
  HandyNotesDungeonLocations, v1.37
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesMoleMachine, v1.1.2
  HandyNotesWarfrontTreasures, v1
  Informant, v8.0.6159 (SwimmingSeadragon)
  MasterPlanA, vA
  NPCScan, v8.0.1.13
  Overachiever, v1.0.3
  OverachieverCache, v1.0.3
  OverachieverTrade, v1.0.3
  Pawn, v2.2.28
  PremadeGroupsFilter, v1.20
  Skada, v1.7.5
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TomTom, vv80001-1.0.2
  WorldQuestTracker, v
  xCT, v4.4.9
  BlizRuntimeLib_ruRU v8.0.1.80000 <none>
  (ck=5c4)

**Comment by journeym** [comment] 2018-09-14 18:43
Also, hangs when entering Azeroth. After addon has been disabled, everything works fine

**Comment by journeym** [comment] 2018-09-14 18:43
Thats RU_ru region

**Comment by idiomatic** [comment] 2018-09-14 22:29
fixed in v0.4.21.

**Closed as completed by idiomatic** 2018-09-14 22:29 UTC

**Comment by idiomatic** [comment] 2018-09-14 23:13
@journeym please comment if this resolves your issue.  thanks.

**Comment by journeym** [comment] 2018-09-16 09:46
All right, the error that a posted no longer appears.
I also managed to track the hanging issue down.
Issue occures when you enable your addon and this one.
https://www.curseforge.com/wow/addons/handynotes_dungeonlocations 
They work fine separately, tested that.
Hangs happen when you port to Azeroth, or open map of eastern kingdoms.
Thied that on EN-gb and RU-ru, cleared cache, disabled all other addons. Nothing helps.

**Comment by idiomatic** [comment] 2018-09-26 17:03
I cannot reproduce a hang with HandyNotes_Achievements v0.4.21 and either of:
* HandyNotes_DungeonLocations 1.38
* HandyNotes_DungeonLocations 1.40
Should you be able to, please submit a [new issue](https://github.com/idiomatic/HandyNotes_Achievements/issues/new).
